version: '3.9'
services:

  zookeeper1:
    image: quay.io/schnell18/zookeeper:3.5.10-1-alpine
    healthcheck:
      test: "nc -z localhost 2181"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      - MAX_HEAP_SIZE=256m
    volumes:
      - ./provision/common/zoo.cfg:/zookeeper/conf/zoo.cfg
      - ./provision/common/log4j.properties:/zookeeper/conf/log4j.properties
      - ../../.state/zookeeper/zk1/data:/var/lib/zookeeper/data
      - ../../.state/zookeeper/zk1/logs:/var/lib/zookeeper/logs
    ports:
      - "2181:2181"
    restart: on-failure

  zookeeper2:
    image: quay.io/schnell18/zookeeper:3.5.10-1-alpine
    healthcheck:
      test: "nc -z localhost 2181"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      - MAX_HEAP_SIZE=256m
    volumes:
      - ./provision/common/zoo.cfg:/zookeeper/conf/zoo.cfg
      - ./provision/common/log4j.properties:/zookeeper/conf/log4j.properties
      - ../../.state/zookeeper/zk2/data:/var/lib/zookeeper/data
      - ../../.state/zookeeper/zk2/logs:/var/lib/zookeeper/logs
    ports:
      - "2182:2181"
    restart: on-failure

  zookeeper3:
    image: quay.io/schnell18/zookeeper:3.5.10-1-alpine
    healthcheck:
      test: "nc -z localhost 2181"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 15
    environment:
      - MAX_HEAP_SIZE=256m
    volumes:
      - ./provision/common/zoo.cfg:/zookeeper/conf/zoo.cfg
      - ./provision/common/log4j.properties:/zookeeper/conf/log4j.properties
      - ../../.state/zookeeper/zk3/data:/var/lib/zookeeper/data
      - ../../.state/zookeeper/zk3/logs:/var/lib/zookeeper/logs
    ports:
      - "2183:2181"
    restart: on-failure
