# dockerized virtual environment
version: '3.9'

services:

  grafana:
    image: docker.io/grafana/grafana:6.0.1
    user: "0"
    environment:
      GF_LOG_LEVEL: error
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    volumes:
      - ./provision/grafana/config/grafana:/etc/grafana
      - ./provision/grafana/config/dashboards:/tmp/dashboards
      - ./.state/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: on-failure

